import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const publicDir = join(root, "backend/public");
const pwaDir = join(root, "backend/resources/pwa");
mkdirSync(pwaDir, { recursive: true });
const html = readFileSync(join(publicDir, "build/index.html"), "utf8");
const version = createHash("sha256").update(html).digest("hex").slice(0, 16);
const assets = readdirSync(join(publicDir, "build/assets")).map(
  (name) => "/build/assets/" + name,
);
const shell = [
  "/build/index.html",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  ...assets,
];
writeFileSync(
  join(publicDir, "sw.js"),
  `// Generated by scripts/build-pwa.mjs. Static shell only; financial responses are never cached.
const CACHE='norocel-shell-${version}';
const ASSETS=${JSON.stringify(shell)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('norocel-shell-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==location.origin||/^\\/(api|auth|sanctum)(\\/|$)/.test(url.pathname)||url.pathname.startsWith('/admin')||url.pathname.startsWith('/backup'))return;
 if(event.request.mode==='navigate'){
  if(!/^\\/(app|login|register|forgot-password|reset-password|operations|accounts|goals|savings|budgets|liabilities|reports|categories|csv|settings|more)(\\/|$)/.test(url.pathname))return;
  event.respondWith(fetch(event.request).catch(()=>caches.match('/build/index.html')));return;
 }
 if(ASSETS.includes(url.pathname))event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(event.request))||fetch(event.request)));
});
`,
);
console.log("PWA static shell " + version);
copyFileSync(join(publicDir, "sw.js"), join(pwaDir, "sw.js"));
copyFileSync(join(publicDir, "manifest.webmanifest"), join(pwaDir, "manifest.webmanifest"));
