server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;
    client_max_body_size 11m;

    location / { try_files $uri $uri/ /index.php?$query_string; }
    location = /sw.js { add_header Cache-Control "no-cache"; }
    location = /manifest.webmanifest { add_header Cache-Control "no-cache"; }
    location /build/assets/ { expires 1y; add_header Cache-Control "public, immutable"; }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
        fastcgi_read_timeout 60s;
    }
    location ~ /\. { deny all; }
}
