@if($kind === 'dashboard')
<div class="app-preview" aria-label="{{ __('site.demo') }}">
    <div class="preview-top"><img class="preview-logo" src="{{ asset('icons/logo.svg') }}" width="1040" height="280" alt="Norocel"><span class="preview-avatar">A</span></div>
    <p class="preview-greeting">{{ __('site.goodDay') }} <span aria-hidden="true">☀</span></p>
    <div class="balance-card"><div><span>{{ __('site.mainBudget') }}</span><span class="currency-pill">MDL</span></div><strong>12 450<span>,00</span></strong><small>{{ __('site.available') }}</small><div class="balance-stats"><span>↙ {{ __('site.income') }}<b>18 000 MDL</b></span><span>↗ {{ __('site.expense') }}<b>4 320 MDL</b></span></div></div>
    <div class="preview-actions">@foreach(['expense' => '↗', 'income' => '↙', 'transfer' => '⇄', 'save' => '↓'] as $key => $symbol)<div><span>{{ $symbol }}</span><small>{{ __('site.'.$key) }}</small></div>@endforeach</div>
    <div class="preview-heading"><strong>{{ __('site.savings') }}</strong><span>→</span></div>
    <div class="preview-accounts"><div><span class="mini-symbol">$</span><small>{{ __('site.reserve') }}</small><strong>1 500 <small>USD</small></strong></div><div><span class="mini-symbol warm">€</span><small>{{ __('site.vacation') }}</small><strong>640 <small>EUR</small></strong></div></div>
    <div class="preview-heading"><strong>{{ __('site.recent') }}</strong><small>{{ __('site.today') }}</small></div>
    <div class="transaction"><span class="transaction-icon">☕</span><span><strong>{{ __('site.coffee') }}</strong><small>{{ __('site.food') }}</small></span><b>−45 MDL</b></div>
    <div class="preview-bottom"><span>⌂</span><span>⇄</span><span class="add">+</span><span>◎</span><span>•••</span></div>
    <span class="demo-label">{{ __('site.demo') }}</span>
</div>
@elseif($kind === 'expenses')
<div class="expense-preview"><div class="preview-heading"><strong>{{ __('site.monthExpenses') }}</strong><span class="currency-pill light">MDL</span></div><div class="expense-summary"><div class="donut"><div><small>{{ __('site.expense') }}</small><strong>4 320</strong><small>MDL</small></div></div><div class="legend"><span><i></i>{{ __('site.food') }}<b>2 160</b></span><span><i></i>{{ __('site.transport') }}<b>1 080</b></span><span><i></i>{{ __('site.home') }}<b>648</b></span><span><i></i>{{ __('site.other') }}<b>432</b></span></div></div><div class="transaction"><span class="transaction-icon">↗</span><span><strong>{{ __('site.groceries') }}</strong><small>{{ __('site.food') }} · {{ __('site.today') }}</small></span><b>−350 MDL</b></div><div class="transaction"><span class="transaction-icon green">↙</span><span><strong>{{ __('site.salary') }}</strong><small>{{ __('site.income') }}</small></span><b class="positive">+18 000 MDL</b></div><div class="transaction"><span class="transaction-icon">⇄</span><span><strong>{{ __('site.betweenAccounts') }}</strong><small>{{ __('site.transfer') }}</small></span><b>500 MDL</b></div><small class="demo-label">{{ __('site.demo') }}</small></div>
@elseif($kind === 'currencies')
<div class="currency-preview"><div class="currency-account main"><span class="feature-icon">@include('components.icon', ['icon' => 'wallet'])</span><div><small>{{ __('site.mainBudget') }}</small><strong>12 450 <span>MDL</span></strong></div><span class="account-status">{{ __('site.everyday') }}</span></div><div class="currency-account"><span class="coin-label">$</span><div><small>{{ __('site.reserve') }}</small><strong>1 500 <span>USD</span></strong></div><span>USD</span></div><div class="currency-account"><span class="coin-label warm">€</span><div><small>{{ __('site.vacation') }}</small><strong>640 <span>EUR</span></strong></div><span>EUR</span></div><p class="currency-caption">{{ __('site.separateCurrency') }}</p><small class="demo-label">{{ __('site.demo') }}</small></div>
@elseif($kind === 'goals')
<div class="goals-preview">@foreach([['name' => 'vacation', 'symbol' => '☀', 'current' => '640', 'target' => '1 500', 'currency' => 'EUR', 'percent' => 43], ['name' => 'laptop', 'symbol' => '⌘', 'current' => '850', 'target' => '1 800', 'currency' => 'USD', 'percent' => 47]] as $goal)<div class="goal-preview"><div class="goal-top"><span class="goal-symbol">{{ $goal['symbol'] }}</span><span><strong>{{ __('site.'.$goal['name']) }}</strong><small>{{ __('site.savingLittle') }}</small></span><b>{{ $goal['percent'] }}%</b></div><p><strong>{{ $goal['current'] }} {{ $goal['currency'] }}</strong><span> / {{ $goal['target'] }} {{ $goal['currency'] }}</span></p><div class="progress" role="img" aria-label="{{ __('site.progress') }} {{ $goal['percent'] }}%"><span style="width:{{ $goal['percent'] }}%"></span></div></div>@endforeach<small class="demo-label">{{ __('site.demo') }}</small></div>
@else
<ol class="steps-preview">@foreach(['stepAccount', 'stepOperation', 'stepGoal'] as $step)<li><span>{{ $loop->iteration }}</span><div><strong>{{ __('site.'.$step) }}</strong><p>{{ __('site.'.$step.'Text') }}</p></div></li>@endforeach</ol>
@endif
